services:
  app:
    build:
      context: .
      dockerfile: images/app.Dockerfile
    env_file:
      - .env
    volumes:
      - .:/workspaces
    working_dir: /workspaces
    command: tail -F /dev/null

